const D=id=>document.getElementById(id);let token='',lastRun='',replayReady=false;
const duration=s=>`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m ${Math.floor(s%60)}s`;
const pct=x=>x==null?'—':`${(x*100).toFixed(1)}%`;
function chart(cells,budget){const el=D('learningChart'),w=el.clientWidth,h=190,ratio=devicePixelRatio||1;el.width=w*ratio;el.height=h*ratio;const c=el.getContext('2d');c.scale(ratio,ratio);c.clearRect(0,0,w,h);c.font='10px Segoe UI';for(let j=0;j<=4;j++){const y=160-j*35;c.strokeStyle='#2c424c';c.beginPath();c.moveTo(35,y);c.lineTo(w-15,y);c.stroke();c.fillStyle='#91a1b3';c.fillText(`${j*25}%`,0,y+4)}const colors={adaptive:'#69e6c2',frozen:'#edb76a',rewired:'#b8a2ff'};let label=0;for(const row of cells.filter(x=>x.seed===0)){c.strokeStyle=colors[row.variant];c.fillStyle=colors[row.variant];c.fillText(row.variant,45+label++*100,14);c.beginPath();row.history.forEach((p,i)=>{const x=35+p.wall_s/budget*(w-50),y=160-p.metric.f1*140;if(i)c.lineTo(x,y);else c.moveTo(x,y)});c.stroke()}c.fillStyle='#91a1b3';c.fillText('0 phút',35,183);c.fillText(`${Math.round(budget/60)} phút`,w-60,183)}
async function refresh(){try{const s=await(await fetch('/api/state')).json();token=s.csrf;const run=s.campaign;const busy=run&&['training','testing','exporting'].includes(run.state);D('startTraining').disabled=busy;D('stopTraining').disabled=!busy;const names={training:'Đang học',testing:'Đánh giá giữ riêng',completed:'Đã hoàn tất',failed:'Có lỗi',interrupted:'Bị gián đoạn'};D('jobState').textContent=run?names[run.state]||run.state:'Chưa có chiến dịch';if(run){D('jobMessage').textContent=run.message;D('realTime').textContent=`${duration(run.elapsed_s)} / ${Math.round(run.budget_s/60)} phút`;D('simTime').textContent=duration(run.aggregate_simulated_s);D('rtf').textContent=`${run.aggregate_rtf.toFixed(2)}×`;D('progressFill').style.width=`${Math.min(100,run.elapsed_s/run.budget_s*100)}%`;const tbody=D('resultsTable').querySelector('tbody');tbody.replaceChildren();for(const row of run.cells){const tr=document.createElement('tr'),m=row.test||row.validation||row.initial_validation||{};for(const v of [`${row.variant} / ${row.seed}${row.test?' · test':''}`,pct(m.precision),pct(m.recall),pct(m.f1),row.generation,duration(row.training_steps*.0002)]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td)}tbody.appendChild(tr)}chart(run.cells,run.budget_s)}
 const unlocked=s.replay.qualified_song_demonstration;document.querySelectorAll('.song').forEach(b=>{if(b.dataset.song!=='skill')b.disabled=!unlocked});D('demoGate').textContent=unlocked?'Đã vượt chuẩn kỹ năng và chuỗi giữ riêng. Hai bài đầy đủ đã mở.':'Hai bài nhạc đang khóa: cần P/R nốt đơn ≥95%, rồi P chuỗi >85% và R/F1 ≥85%. Có thể xem replay kỹ năng chẩn đoán bên dưới.';
 if(!s.replay.preview&&!replayReady&&window.flyPiano){replayReady=true;window.flyPiano.load('skill')}lastRun=run?.run_id||'';
 }catch(e){D('jobMessage').textContent=`Không đọc được trạng thái: ${e.message}`}}
async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-FlyPiano-Token':token},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error);return v}
D('startTraining').onclick=async()=>{try{D('startTraining').disabled=true;await post('/api/train',{minutes:Number(D('minutes').value),workers:4});replayReady=false;setTimeout(refresh,1200)}catch(e){D('jobMessage').textContent=e.message}};
D('stopTraining').onclick=async()=>{try{await post('/api/stop',{});D('jobMessage').textContent='Sẽ dừng sau lô hiện tại rồi đánh giá checkpoint đã chọn.'}catch(e){D('jobMessage').textContent=e.message}};
refresh();setInterval(refresh,4000);
