'use strict';
const $=s=>document.querySelector(s);let data,atlas,frame=0,playing=false,angle=.2,tilt=.1,last=0,runs=[];
function canvas(id){const c=$(id),r=c.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;const ctx=c.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);return [ctx,r.width,r.height]}
function clear(ctx,w,h){ctx.fillStyle='#0a151f';ctx.fillRect(0,0,w,h)}
function color(x,max=250){const v=Math.max(0,Math.min(1,x/max));return `rgb(${Math.round(40+180*v)},${Math.round(75+175*v)},${Math.round(100+100*(1-v))})`}
function text(ctx,str,x,y,size=12,col='#a6bdcc'){ctx.font=`${size}px system-ui`;ctx.fillStyle=col;ctx.fillText(str,x,y)}
function drawAnatomy(){const [c,w,h]=canvas('#anatomy');clear(c,w,h);if(!atlas)return;const verts=atlas.neuropils.vertices_um,regions=atlas.neuropils.regions_one_based;
 const project=v=>{let x=(v[0]-210)/2.1,y=(v[1]-210)/2.1,z=(v[2]-330)/2.1;return [w/2+x*Math.cos(angle)+y*Math.sin(angle),h/2+z*.86+(y*Math.cos(angle)-x*Math.sin(angle))*tilt]};
 for(const [name,faces] of Object.entries(regions)){let reg=(name.match(/T[123]/)||['neck connective'])[0];const ids=data.neurons.map((n,i)=>n.region===reg?i:-1).filter(i=>i>=0);const val=ids.length?ids.reduce((a,i)=>a+data.frames.rates[frame][i],0)/ids.length:0;c.strokeStyle=color(val,20);c.globalAlpha=.25+Math.min(val/20,.7);c.lineWidth=.45;
 for(let i=0;i<faces.length;i+=35){const f=faces[i];c.beginPath();f.forEach((id,j)=>{const p=project(verts[id-1]);j?c.lineTo(...p):c.moveTo(...p)});c.closePath();c.stroke()}}
 c.globalAlpha=1;text(c,'VNC / native MANC coordinates',15,23,12);text(c,'Brain anatomy: not included',15,h-18,11,'#daa766')}
function drawBody(){const [c,w,h]=canvas('#body');clear(c,w,h);const sx=x=>w/2+x*w*.33,sy=z=>h*.15-z*h*.72;const q=data.frames.q[frame],force=data.frames.force[frame],key=data.frames.target[frame];
 data.key_x.forEach((x,i)=>{const kw=w*.33*Math.abs(data.key_x[1]-data.key_x[0])*.85;c.fillStyle=force.some((f,l)=>f>.04&&data.frames.actual[frame][l]===i)?'#58e4b0':i===key?'#d6ad62':'#95aab6';c.fillRect(sx(x)-kw/2,sy(data.key_height),kw,28);text(c,String(i),sx(x)-3,sy(data.key_height)+43,11)});
 c.fillStyle='#50687b';c.beginPath();c.ellipse(w/2,37,65,22,0,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(w/2+72,32,22,19,0,0,Math.PI*2);c.fill();
 for(let i=5;i>=0;i--){const hip=data.hips[i],a=q[i][0],b=a+q[i][1],k=[hip[0]+.65*Math.cos(a),hip[1]+.65*Math.sin(a)],foot=[k[0]+.65*Math.cos(b),k[1]+.65*Math.sin(b)];c.strokeStyle=['#65dacf','#dca4e5','#72a2de','#dbb66a','#a0c76b','#de857d'][i];c.lineWidth=3;c.beginPath();c.moveTo(sx(hip[0]),sy(hip[1]));c.lineTo(sx(k[0]),sy(k[1]));c.lineTo(sx(foot[0]),sy(foot[1]));c.stroke();c.fillStyle=force[i]>.04?'#73ffb8':c.strokeStyle;c.beginPath();c.arc(sx(foot[0]),sy(foot[1]),force[i]>.04?6:3,0,7);c.fill();text(c,['LF','RF','LM','RM','LH','RH'][i],sx(k[0])+4,sy(k[1])-4,9)}
 text(c,'2R torque dynamics · tethered body',14,20,11);}
let rasterImage;
function makeRaster(){const off=document.createElement('canvas');off.width=data.frames.time.length;off.height=data.neurons.length;const c=off.getContext('2d'),im=c.createImageData(off.width,off.height);for(let t=0;t<off.width;t++)for(let n=0;n<off.height;n++){const v=Math.min(1,data.frames.rates[t][n]/250),i=(n*off.width+t)*4;im.data[i]=30+220*v;im.data[i+1]=35+210*v;im.data[i+2]=60+100*v;im.data[i+3]=255}c.putImageData(im,0,0);rasterImage=off}
function drawRaster(){const [c,w,h]=canvas('#raster');c.drawImage(rasterImage,0,0,w,h);c.strokeStyle='#e3eef2';c.beginPath();c.moveTo(frame/(data.frames.time.length-1)*w,0);c.lineTo(frame/(data.frames.time.length-1)*w,h);c.stroke()}
function drawPath(){const [c,w,h]=canvas('#path');clear(c,w,h);const selected=Number($('#neuron').value||0),node=data.neurons[selected];const downstream=node.downstream.slice(0,9),source=[w*.18,h/2];
 for(let j=0;j<downstream.length;j++){const d=downstream[j],i=data.neurons.findIndex(n=>n.id===d.id),p=[w*.7,20+j*(h-30)/Math.max(1,downstream.length)];c.strokeStyle=d.signed_synapses<0?'#da809c':'#56c8ac';c.globalAlpha=.25+Math.min(data.frames.rates[frame][selected]/250,.75);c.beginPath();c.moveTo(...source);c.lineTo(...p);c.stroke();c.globalAlpha=1;c.fillStyle=color(data.frames.rates[frame][i]);c.beginPath();c.arc(...p,4,0,7);c.fill();text(c,`${d.id} (${d.signed_synapses})`,p[0]+9,p[1]+3,9)}c.fillStyle=color(data.frames.rates[frame][selected]);c.beginPath();c.arc(...source,10,0,7);c.fill();text(c,node.id,10,22,12);text(c,node.type,10,40,11);text(c,'First 9 structural targets',10,h-12,10)}
function drawTask(){const [c,w,h]=canvas('#task');clear(c,w,h);data.frames.task[frame].forEach((x,i)=>{c.fillStyle=color(x,1);c.fillRect(18+i*(w-36)/8,h-30-x*(h-60),(w-50)/9,x*(h-60)+1);text(c,String(i),22+i*(w-36)/8,h-12,10)});text(c,'Synthetic units · no anatomical IDs',14,20,11)}
function inspect(){const i=Number($('#neuron').value||0),n=data.neurons[i],t=data.frames.time[frame];const contact=data.metadata.contacts.filter(x=>x.time<=t).at(-1);$('#details').textContent='';const lines=[`Neuron ${n.id} / ${n.type}`,`Region: ${n.region} | ${n.kind}`,`t = ${t.toFixed(3)} s | raw index ${data.frames.raw_index[frame]}`,`Modeled rate: ${data.frames.rates[frame][i].toFixed(3)} Hz`,`Predicted NT: ${n.nt} (${(n.confidence===null?'unknown':n.confidence.toFixed(3))})`,`Source: ${n.source}`,`Downstream targets: ${n.downstream.length}`,`Anatomical arbor mapping: unavailable`,contact?`Last contact: key ${contact.key}, limb ${['LF','RF','LM','RM','LH','RH'][contact.limb]}, t ${contact.time.toFixed(3)}`:'No contact yet',contact?`Expected ${contact.expected_key}; error ${contact.timing_error_s?.toFixed(3)} s; force ${contact.force.toFixed(3)}`:'',contact?`Readout member: ${contact.responsible_mn_id}`:'',contact?`Structural upstream: ${(contact.structural_upstream_path||[]).join(' > ')||'no path'}`:''];for(const l of lines){let p=document.createElement('div');p.textContent=l;$('#details').append(p)}}
function draw(){if(!data)return;drawAnatomy();drawBody();drawRaster();drawPath();drawTask();inspect();$('#seek').value=frame;$('#time').textContent=data.frames.time[frame].toFixed(3)+' s'}
function fill(sel,values,preferred){$(sel).replaceChildren(...values.map(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;return o}));if(values.includes(preferred))$(sel).value=preferred}
function availableParts(){return runs.map(r=>{let p=r.id.split('_');return {id:r.id,exp:p[0],seed:p.at(-1),rest:p.slice(1,-1).join('_')}})}
let config=[];function updateConditions(){let c=config.filter(c=>c.experiment_id==$('#experiment').value);fill('#condition',[...new Set(c.map(c=>c.condition))],'novel');updateVariants()}function updateVariants(){let c=config.filter(c=>c.experiment_id==$('#experiment').value&&c.condition==$('#condition').value);fill('#variant',[...new Set(c.map(c=>c.variant))],'full');fill('#seed',[...new Set(c.map(c=>String(c.seed)))],'0')}
function id(){return `${$('#experiment').value}_${$('#condition').value}_${$('#variant').value}_s${$('#seed').value.padStart(2,'0')}`}
async function load(){playing=false;$('#play').textContent='Play';$('#status').textContent='Reading telemetry…';try{const response=await fetch('/api/replay?id='+encodeURIComponent(id()));let d=await response.json();if(!response.ok)throw Error(d.error);data=d;frame=0;$('#seek').max=data.frames.time.length-1;fill('#neuron',data.neurons.map((n,i)=>String(i)),'0');[...$('#neuron').options].forEach((o,i)=>o.textContent=data.neurons[i].id+' · '+data.neurons[i].type);makeRaster();$('#metrics').textContent='';for(const [label,v] of [['Key accuracy',data.metrics.key_accuracy],['Rhythm power',data.metrics.motor_rhythm_power],['Timing MAE (s)',data.metrics.timing_mae_s],['Contacts',data.metrics.contact_count]]){let div=document.createElement('div'),n=document.createElement('div'),l=document.createElement('small');n.className='number';n.textContent=v===null?'N/A':typeof v==='number'?v.toFixed(label==='Contacts'?0:3):v;l.textContent=label;div.append(n,l);$('#metrics').append(div)}$('#status').textContent=data.metadata.run_id+' · '+data.metadata.hypothesis+' | Body driver: '+data.body_driver;$('#provenance').textContent=`Git ${data.metadata.git_commit} | ${data.metadata.dataset_version} | Config ${data.metadata.config_sha256} | Raw ${data.metadata.telemetry_sha256}`;draw()}catch(e){$('#status').textContent=e.message}}
$('#load').onclick=load;$('#experiment').onchange=updateConditions;$('#condition').onchange=updateVariants;$('#neuron').onchange=draw;$('#seek').oninput=e=>{frame=Number(e.target.value);draw()};$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'Pause':'Play';last=0};$('#run').onclick=async()=>{if(!confirm('Execute '+id()+' with its registered parameters? Existing replay for this ID will be regenerated.'))return;$('#status').textContent='Running selected experiment…';const r=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id()})});if(r.ok)load();else $('#status').textContent=(await r.json()).error};$('#export').onclick=()=>{if(!data)return;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download=data.metadata.run_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
let drag;$('#anatomy').onpointerdown=e=>{drag=[e.clientX,e.clientY];e.target.setPointerCapture(e.pointerId)};$('#anatomy').onpointermove=e=>{if(drag){angle+=(e.clientX-drag[0])*.008;tilt+=(e.clientY-drag[1])*.003;drag=[e.clientX,e.clientY];drawAnatomy()}};$('#anatomy').onpointerup=()=>drag=null;
function tick(t){if(playing&&data){if(!last)last=t;if(t-last>40/Number($('#speed').value)){frame=(frame+1)%data.frames.time.length;last=t;draw()}}requestAnimationFrame(tick)}requestAnimationFrame(tick);window.onresize=draw;
Promise.all([fetch('/experiments/registry.json').then(r=>r.json()),fetch('/connectome/anatomy.json').then(r=>r.json())]).then(([c,a])=>{config=c;atlas=a;fill('#experiment',[...new Set(c.map(c=>c.experiment_id))],'B1');updateConditions();load()}).catch(e=>$('#status').textContent=e.message);


