import * as THREE from 'three';
import {NeuralView} from './neural_view.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id),state={time:0,playing:false,song:'skill',variant:'adaptive',ready:false,loading:0};
let neuralView;
let sceneData,score,replay,frames,body,brain,flyMeshes=[],keys=[],neuronLines=[],surface,context,audioCursor=0,last=performance.now();
const fmt=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const percent=x=>`${(x*100).toFixed(1)}%`;
async function json(url){const r=await fetch(url);if(!r.ok)throw Error(`${url}: HTTP ${r.status}`);return r.json()}
function setup(id,position,target){const element=$(id),scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;element.appendChild(renderer.domElement);const camera=new THREE.PerspectiveCamera(36,1,.001,10000);camera.up.set(0,0,1);camera.position.fromArray(position);const controls=new OrbitControls(camera,renderer.domElement);controls.target.fromArray(target);controls.enableDamping=true;controls.dampingFactor=.1;controls.update();scene.add(new THREE.HemisphereLight(0xd9eeff,0x34433f,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(3,2,8);scene.add(light);const resize=()=>{renderer.setSize(element.clientWidth,element.clientHeight);camera.aspect=element.clientWidth/element.clientHeight;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(element);resize();return{scene,renderer,camera,controls,element,position,target}}
function geometry(vertices,faces){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices.flat(),3));g.setIndex(faces.flat());g.computeVertexNormals();return g}
function buildBody(data){body=setup('bodyView',[7.1,6.4,5.6],[0,0,.5]);for(const part of data.geoms){const color=new THREE.Color().setRGB(...part.color.slice(0,3));const material=new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.08,side:THREE.DoubleSide,transparent:/wing/.test(part.name),opacity:/wing/.test(part.name)?.36:1});const mesh=new THREE.Mesh(geometry(part.vertices,part.faces),material);mesh.matrixAutoUpdate=false;body.scene.add(mesh);flyMeshes.push(mesh)}for(let pitch=21;pitch<=108;pitch++){const black=[1,3,6,8,10].includes(pitch%12);const mesh=new THREE.Mesh(new THREE.BoxGeometry(4.5,data.key_spacing*.9,.05),new THREE.MeshStandardMaterial({color:black?0x192536:0x9eabb5,roughness:.7}));mesh.position.set(0,(pitch-64)*data.key_spacing,data.key_z-.025);mesh.userData.base=mesh.material.color.clone();body.scene.add(mesh);keys.push(mesh)}const plate=new THREE.Mesh(new THREE.BoxGeometry(4.75,5.15,.13),new THREE.MeshStandardMaterial({color:0x263a4e,roughness:.6,metalness:.3}));plate.position.z=data.key_z-.16;body.scene.add(plate);const floor=new THREE.GridHelper(16,32,0x314255,0x243143);floor.rotation.x=Math.PI/2;floor.position.z=-.4;body.scene.add(floor)}
function buildBrain(data){brain=setup('brainView',[0,-660,430],[0,0,0]);surface=new THREE.Mesh(geometry(data.vertices,data.faces),new THREE.MeshPhongMaterial({color:0x89a6c2,transparent:true,opacity:.09,side:THREE.DoubleSide,depthWrite:false}));brain.scene.add(surface);for(let i=0;i<data.neurons.length;i++){const n=data.neurons[i],positions=[];for(const [a,b]of n.edges)positions.push(...n.vertices[a],...n.vertices[b]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));const material=new THREE.LineBasicMaterial({color:i?0xf691b7:0x58c9f2,transparent:true,opacity:.7});const lines=new THREE.LineSegments(g,material);lines.userData=n;brain.scene.add(lines);neuronLines.push(lines)}$('brainSurface').onchange=()=>surface.visible=$('brainSurface').checked}
function seek(t){state.time=Math.max(0,Math.min(replay?.duration??0,t));audioCursor=state.time;update();return state.time}
function noteSound(pitch,duration,velocity=.13){if(!context)return;const f=440*2**((pitch-69)/12),now=context.currentTime;for(let h=1;h<=3;h++){const osc=context.createOscillator(),gain=context.createGain();osc.type='sine';osc.frequency.value=f*h;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(velocity/(h*h),now+.005);gain.gain.exponentialRampToValueAtTime(.0001,now+Math.min(2.5,Math.max(.06,duration)));osc.connect(gain);gain.connect(context.destination);osc.start(now);osc.stop(now+Math.min(2.6,Math.max(.08,duration))+.02)}}
function audioStep(){if(!context||$('audio').value==='none'){audioCursor=state.time;return}const events=$('audio').value==='reference'?score.notes:replay.actual;for(const n of events)if(n.start>=audioCursor&&n.start<state.time)noteSound(n.pitch,(n.end-n.start)/Number($('speed').value));audioCursor=state.time}
function drawRoll(){const canvas=$('roll'),ratio=devicePixelRatio||1,w=canvas.clientWidth,h=190;if(canvas.width!==Math.round(w*ratio)){canvas.width=Math.round(w*ratio);canvas.height=h*ratio}const c=canvas.getContext('2d');c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,w,h);c.fillStyle='#0d1520';c.fillRect(0,0,w,h);const left=state.time-2.0,span=10,width=w-44,row=(h-20)/88,x=t=>44+(t-left)/span*width,y=p=>8+(108-p)*row;c.strokeStyle='#253243';c.lineWidth=1;for(let p=24;p<=108;p+=12){c.beginPath();c.moveTo(40,y(p));c.lineTo(w,y(p));c.stroke();c.fillStyle='#687c92';c.font='9px Segoe UI';c.fillText(`C${p/12-1}`,7,y(p)+3)}for(const b of score.bars)if(b.start>=left&&b.start<=left+span){c.strokeStyle='#233246';c.beginPath();c.moveTo(x(b.start),0);c.lineTo(x(b.start),h);c.stroke();c.fillStyle='#687c92';c.fillText(b.measure,x(b.start)+3,h-4)}for(const n of score.notes){if(n.end<left||n.start>left+span)continue;c.fillStyle='#b98d57';c.fillRect(x(n.start),y(n.pitch),Math.max(2,x(n.end)-x(n.start)),Math.max(1.1,row*.8))}for(const n of replay.actual){if(n.end<left||n.start>left+span)continue;c.fillStyle='#69e6c2';c.fillRect(x(n.start),y(n.pitch)+row*.4,Math.max(2,x(n.end)-x(n.start)),Math.max(1,row*.4))}c.strokeStyle='#effbf7';c.beginPath();c.moveTo(x(state.time),0);c.lineTo(x(state.time),h);c.stroke()}
const matrix=new THREE.Matrix4();
let falling=[];const cueHorizon=.15;
function buildFalling(){for(const mesh of falling){body.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose()}falling=[];for(let i=0;i<48;i++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.5,sceneData.key_spacing*.65,1),new THREE.MeshBasicMaterial({color:0xedb76a,transparent:true,opacity:.65,depthWrite:false}));mesh.visible=false;body.scene.add(mesh);falling.push(mesh)}}
function updateFalling(){const t=state.time;const notes=score.notes.filter(n=>n.start<=t+cueHorizon&&n.end>=t).slice(0,48);falling.forEach((mesh,i)=>{const n=notes[i];mesh.visible=!!n;if(!n)return;const head=Math.max(0,n.start-t)*8,tail=Math.min(cueHorizon,Math.max(0,n.end-t))*8;mesh.scale.z=Math.max(.015,tail-head);mesh.position.set(-1.65,(n.pitch-64)*sceneData.key_spacing,sceneData.key_z+.05+(head+tail)/2);mesh.material.color.setHex(n.start<=t?0xf8d29c:0xedb76a)})}

function update(){if(!state.ready)return;const frame=Math.min(replay.frame_count-1,Math.floor(state.time*replay.fps)),base=frame*replay.stride;for(let i=0;i<flyMeshes.length;i++){const o=base+i*12;matrix.set(frames[o+3],frames[o+4],frames[o+5],frames[o],frames[o+6],frames[o+7],frames[o+8],frames[o+1],frames[o+9],frames[o+10],frames[o+11],frames[o+2],0,0,0,1);flyMeshes[i].matrix.copy(matrix);flyMeshes[i].matrixWorldNeedsUpdate=true}const kd=base+replay.layout.key_displacement[0],target=new Set(score.notes.filter(n=>n.start<=state.time&&n.end>state.time).map(n=>n.pitch)),actual=new Set(replay.actual.filter(n=>n.start<=state.time&&n.end>state.time).map(n=>n.pitch));for(let i=0;i<keys.length;i++){const k=keys[i];k.position.z=sceneData.key_z-.025+frames[kd+i];k.material.color.copy(k.userData.base);k.material.emissive.setHex(actual.has(i+21)?0x2d987d:target.has(i+21)?0x9e6020:0);k.material.emissiveIntensity=.8}const cp=base+replay.layout.CPG[0];for(let i=0;i<18;i++){const el=$('cpg'+i);el.style.opacity=.15+.85*Math.min(1,frames[cp+i]/50);el.title='CPG '+i+': '+frames[cp+i].toFixed(2)+' đơn vị rate; thang 0–50'}const dn=base+replay.layout.DN[0];for(let i=0;i<2;i++){const value=frames[dn+i];neuronLines[i].material.opacity=.12+.88*Math.min(1,value/50);$(i?'dnRight':'dnLeft').textContent=value.toFixed(1)}const mn=base+replay.layout.MN[0],gate=base+replay.layout.gate[0];for(let i=0;i<6;i++){$(`leg${i}`).style.height=`${Math.min(1,frames[gate+i])*100}%`;$(`leg${i}`).parentElement.title=`MN sum/40: ${frames[mn+i].toFixed(3)}; press gate: ${frames[gate+i].toFixed(3)}`}$('clock').textContent=`${fmt(state.time)} / ${fmt(replay.duration)}`;$('seek').value=state.time;const bar=score.bars.find(b=>b.start<=state.time&&b.end>state.time);$('measure').textContent=bar?`Ô ${bar.measure} · trang ${bar.page}/${score.pages} · ${bar.meter}`:(state.song==='skill'?'Chuỗi tổng hợp':'Kết thúc');drawRoll();updateFalling();neuralView?.update(replay,frames,frame);body.renderer.render(body.scene,body.camera);brain.renderer.render(brain.scene,brain.camera)}
async function load(song,variant='adaptive'){
 const token=++state.loading;state.playing=false;state.ready=false;$('play').disabled=true;$('play').textContent='Đang tải…';
 try{const r=await json(`/replay/${song}.json`);const s=song==='skill'?{title:`Kiểm tra 100 nốt · ${r.checkpoint_label||'checkpoint v4b trước luyện hai bài'}`,notes:r.notes,bars:[],pages:0,warnings:[]}:await json(`/data/${song}_score.json`);
 const response=await fetch(`/replay/${song}.bin`);if(!response.ok)throw Error('Replay chưa sẵn sàng');const array=new Float32Array(await response.arrayBuffer());if(token!==state.loading)return;if(array.length!==r.frame_count*r.stride)throw Error('Sai kích thước replay');
 if(song!=='skill' && r.notes)s.notes=r.notes;score=s;replay=r;frames=array;state.song=song;state.variant=variant;state.ready=true;state.time=0;audioCursor=0;$('seek').max=r.duration;$('sheet').hidden=song==='skill';$('midi').hidden=song==='skill';if(song!=='skill'){$('sheet').href=s.source_pdf;$('midi').href=`/data/${song}_reference.mid`}
 $('songTitle').textContent=s.title;$('brainScope').textContent='Chiếu rate DN mô phỏng lên 2 DNg100 đồng dạng FlyWire; khác cá thể/giới tính. Không phải hoạt động não đo được. Thang cố định 0–50. Synapse học nằm trong mô hình VNC; không suy từ độ sáng DN rằng vùng này đã học.';
 $('scoreStatus').textContent=song==='skill'?'Chuỗi tổng hợp, có cao độ và thời gian xác định. Nốt rơi chỉ hiển thị 150 ms phía trước. Replay chẩn đoán không đồng nghĩa vượt chuẩn.':`${s.notes.length} nốt toàn bài · OMR chưa được kiểm tra độc lập từng nốt · ${s.warnings.length} cảnh báo ô nhịp.`;
 const m=r.metrics.find(m=>m.tolerance_s===.1);$('recall').textContent=percent(m.recall);$('precision').textContent=percent(m.precision);$('f1').textContent=percent(m.f1);$('counts').textContent=`${m.matched}/${m.target_notes} nốt đúng · ${m.missed} thiếu · ${m.extra} thừa. Ghép một-một từ tiếp xúc vật lý, ±100 ms.`;
 $('loadState').textContent=`${r.preview?'Chưa học · ':''}${r.physics_steps.toLocaleString('vi')} bước vật lý · ${r.solver_warnings} cảnh báo`;buildFalling();$('play').disabled=false;$('play').textContent='▶ Phát mô phỏng';document.querySelectorAll('.song').forEach(b=>b.classList.toggle('selected',b.dataset.song===song));update()
 }catch(e){$('loadState').textContent=e.message;$('play').textContent='Chưa có replay';console.error(e)}
}
function animate(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(state.ready){if(state.playing){state.time=Math.min(replay.duration,state.time+dt*Number($('speed').value));audioStep();if(state.time>=replay.duration){state.playing=false;$('play').textContent='↻ Phát lại'}}body.controls.update();brain.controls.update();update()}requestAnimationFrame(animate)}
for(const [i,name] of ['Trước T','Trước P','Giữa T','Giữa P','Sau T','Sau P'].entries())$('legRates').insertAdjacentHTML('beforeend',`<div class="leg"><div class="barTrack"><div class="barFill" id="leg${i}"></div></div>${name}</div>`);
$('play').onclick=async()=>{if(!state.ready)return;if(!context)context=new AudioContext();await context.resume();if(state.time>=replay.duration)seek(0);state.playing=!state.playing;audioCursor=state.time;$('play').textContent=state.playing?'Ⅱ Tạm dừng':'▶ Phát mô phỏng'};$('seek').oninput=()=>seek(Number($('seek').value));$('audio').onchange=async()=>{if(!context)context=new AudioContext();await context.resume();audioCursor=state.time};$('variant').onchange=()=>load(state.song,$('variant').value).catch(console.error);document.querySelectorAll('.song').forEach(b=>b.onclick=()=>load(b.dataset.song,$('variant').value).catch(console.error));$('resetView').onclick=()=>{for(const view of [body,brain]){view.camera.position.fromArray(view.position);view.controls.target.fromArray(view.target);view.controls.update()}};
window.flyPiano={state,seek,load,render:()=>update(),get score(){return score},get replay(){return replay}};
try{const [s,b]=await Promise.all([json('/assets/scene.json'),json('/assets/brain.json')]);sceneData=s;buildBody(s);buildBrain(b);neuralView=new NeuralView(await json('/assets/manc.json'));window.flyPiano.neural=neuralView;await load('skill');requestAnimationFrame(animate)}catch(e){$('loadState').textContent=e.message;console.error(e)}
