const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('fs'),path=require('path');
(async()=>{const out=path.resolve(__dirname,'qa');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8879/',{waitUntil:'networkidle',timeout:120000});await page.waitForFunction(()=>window.flyPiano?.state.ready&&flyPiano.neural.valid,{},{timeout:120000});
 const result=await page.evaluate(()=>{flyPiano.seek(15);const n=flyPiano.neural;return {targets:flyPiano.score.notes.length,neurons:n.mapping.length,validGeometry:n.data.neurons.filter(x=>x.coordinate_valid).length,active:n.active,ratesFinite:n.rates.every(Number.isFinite)}});
 if(result.targets!==100||result.neurons!==412||result.validGeometry!==410||!result.ratesFinite)throw Error(JSON.stringify(result));
 await page.locator('#neuralRegion').selectOption('T1');await page.waitForTimeout(100);const filter=await page.evaluate(()=>flyPiano.neural.lines.every((x,i)=>!x.visible||flyPiano.neural.data.neurons[i].region==='T1'));if(!filter)throw Error('Region filter mismatch');
 await page.locator('#neuralRegion').selectOption('all');await page.locator('#activeOnly').check();await page.waitForTimeout(100);if(!await page.evaluate(()=>flyPiano.neural.lines.every((x,i)=>!x.visible||flyPiano.neural.rates[i]>1)))throw Error('Activity filter mismatch');await page.locator('#activeOnly').uncheck();
 await page.locator('.neuralPanel').screenshot({path:path.join(out,'neural.jpg'),type:'jpeg',quality:90});await page.screenshot({path:path.join(out,'app.jpg'),fullPage:true,type:'jpeg',quality:82});
 await page.locator('#play').click();await page.waitForTimeout(300);await page.locator('#play').click();const t=await page.evaluate(()=>flyPiano.state.time);await page.waitForTimeout(150);if(t!==await page.evaluate(()=>flyPiano.state.time))throw Error('Pause failed');
 await page.setViewportSize({width:760,height:1000});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow');await page.screenshot({path:path.join(out,'narrow.jpg'),fullPage:true,type:'jpeg',quality:75});
 const response=await page.request.post('http://127.0.0.1:8879/api/train',{data:{minutes:1}});if(response.status()!==403)throw Error('Missing CSRF protection');if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(path.join(out,'ui_check.json'),JSON.stringify({...result,filter,errors,pause:true,narrow:true,csrf:true},null,2));console.log('UI verified',result);
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
